### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by nksaraf** [nksaraf/vinxi#88]
- [ ] #84 `passthrough` for public assets (dev & prod)
- [ ] #78 check all variations of `preset` being passed and the precedence rules related to that (just need to check build setup probably)
- [ ] #79 test css/asset loading extensively across setups (this is kindof testing the Manifest)
- [ ] #55 `baseURL` server
- [ ] #47 devProxy
